name: GitHub Pages deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build website
        run: npm run build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist